# Generated by Django 2.1.7 on 2022-07-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenum',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
