# Generated by Django 2.1.7 on 2022-07-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phonenum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schoolssn',
        ),
    ]
